# Generated by Django 5.2.8 on 2025-11-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
